/*
 * sound/soc/codec/ak4671_gaintable.h
 *
 * Copyright (C) 2009 Samsung Electronics.
 *
 */

/* gain table flag */
/* Gain tunning point : available*/
#define MGNL_MICAMP_LGAIN			0	
#define MGNR_MICAMP_RGAIN			1	
#define L1G_IN1_GAIN					2		
#define L2G_IN2_GAIN					3		
#define L3G_IN3_GAIN					4		
#define L4G_IN4_GAIN					5		
#define LPG_MICAMP_GAIN					6		
#define IVL_ALC_LGAIN					7		
#define IVR_ALC_RGAIN					8
#define OVL_DATT_LGAIN					9
#define OVR_DATT_RGAIN					10
#define BVL_DATTB_GAIN					11
#define L1VL_OUT1_RCV_GAIN				12
#define HPG_OUT2_SPK_HP_GAIN			13		
#define L3VL_OUT3_MSMSPK_GAIN			14
#define PGAINA_AMP_GAIN					15
#define PGAINB_AMP_GAIN					16
#define SVOL_AMP_GAIN					17
#define HPLVOL_AMP_LGAIN				18
#define HPRVOL_AMP_RGAIN				19


#define NORMAL_STATE            (0x0000)
#define TALKING_STATE           (0x1000)
#define RECORDING_STATE         (0x2000)

#define MODE_MP3PLAY            (NORMAL_STATE + 0x0010)
#define MODE_VIDEOPLAY          (NORMAL_STATE + 0x0020)
#define MODE_RINGTONEPLAY       (NORMAL_STATE + 0x0040)
#define MODE_KEYTONEPLAY        (NORMAL_STATE + 0x0080)
#define MODE_FMRADIOPLAY        (NORMAL_STATE + 0x0100)
#define MODE_CAMERAPLAY         (NORMAL_STATE + 0x0200)
#define MODE_GAMETONE           (NORMAL_STATE + 0x0400)

#define MODE_VOICERECORDING     (RECORDING_STATE + 0x0010)
#define MODE_CAMCORDING         (RECORDING_STATE + 0x0020)
#define MODE_FMRECORDING        (RECORDING_STATE + 0x0040)

#define MODE_VOICECALL          (TALKING_STATE + 0x0010)
#define MODE_VIDEOCALL          (TALKING_STATE + 0x0020)

#define SOUND_PATH_SPEAKER      (0x0001)
#define SOUND_PATH_RECEIVER     (0x0002)
#define SOUND_PATH_HEADSET      (0x0004)
#define SOUND_PATH_BLUETOOTH    (0x0008)

#define SOUND_PATH_MAINMIC      (0x0001)
#define SOUND_PATH_HEADSETMIC   (0x0002)
#define SOUND_PATH_FMINPUT      (0x0004)

/* sound scenario enum */
#define DEFAULT_GAIN					0X0000

#define NORMAL_MP3_SPEAKER              (MODE_MP3PLAY + SOUND_PATH_SPEAKER)
#define NORMAL_MP3_HEADSET              (MODE_MP3PLAY + SOUND_PATH_HEADSET)

#define NORMAL_VIDEO_SPEAKER            (MODE_VIDEOPLAY + SOUND_PATH_SPEAKER)
#define NORMAL_VIDEO_HEADSET            (MODE_VIDEOPLAY + SOUND_PATH_HEADSET)

#define NORMAL_RINGTONE_SPEAKER         (MODE_RINGTONEPLAY + SOUND_PATH_SPEAKER)
#define NORMAL_RINGTONE_HEADSET         (MODE_RINGTONEPLAY + SOUND_PATH_HEADSET)
#define NORMAL_RINGTONE_BLUETOOTH       (MODE_RINGTONEPLAY + SOUND_PATH_BLUETOOTH)

#define NORMAL_KEYTONE_SPEAKER          (MODE_KEYTONEPLAY + SOUND_PATH_SPEAKER)
#define NORMAL_KEYTONE_HEADSET          (MODE_KEYTONEPLAY + SOUND_PATH_HEADSET)
#define NORMAL_KEYTONE_BLUETOOTH        (MODE_KEYTONEPLAY + SOUND_PATH_BLUETOOTH)

#define NORMAL_CAMERA_SPEAKER           (MODE_CAMERAPLAY + SOUND_PATH_SPEAKER)
#define NORMAL_CAMERA_HEADSET           (MODE_CAMERAPLAY + SOUND_PATH_HEADSET)
#define NORMAL_CAMERA_BLUETOOTH         (MODE_CAMERAPLAY + SOUND_PATH_BLUETOOTH)

#define NORMAL_GAMETONE_SPEAKER         (MODE_GAMETONE + SOUND_PATH_SPEAKER)
#define NORMAL_GAMETONE_HEADSET         (MODE_GAMETONE + SOUND_PATH_HEADSET)
#define NORMAL_GAMETONE_BLUETOOTH       (MODE_GAMETONE + SOUND_PATH_BLUETOOTH)

#define NORMAL_FMRADIO_SPEAKER          (MODE_FMRADIOPLAY + SOUND_PATH_SPEAKER)
#define NORMAL_FMRADIO_HEADSET          (MODE_FMRADIOPLAY + SOUND_PATH_HEADSET)

#define NORMAL_VOICEREC_MAINMIC         (MODE_VOICERECORDING + SOUND_PATH_MAINMIC)
#define NORMAL_VOICEREC_HEADSETMIC      (MODE_VOICERECORDING + SOUND_PATH_HEADSETMIC)

#define NORMAL_CAMCORDING_MAINMIC       (MODE_CAMCORDING + SOUND_PATH_MAINMIC)
#define NORMAL_CAMCORDING_HEADSETMIC    (MODE_CAMCORDING + SOUND_PATH_HEADSETMIC)

#define NORMAL_FMREC_FMINPUT            (MODE_FMRECORDING + SOUND_PATH_FMINPUT)

#define TALKING_VOICECALL_RECEIVER      (MODE_VOICECALL + SOUND_PATH_RECEIVER)
#define TALKING_VOICECALL_SPEAKER       (MODE_VOICECALL + SOUND_PATH_SPEAKER)
#define TALKING_VOICECALL_HEADSET       (MODE_VOICECALL + SOUND_PATH_HEADSET)
#define TALKING_VOICECALL_BLUETOOTH     (MODE_VOICECALL + SOUND_PATH_BLUETOOTH)

#define TALKING_VIDEOCALL_RECEIVER      (MODE_VIDEOCALL + SOUND_PATH_RECEIVER)
#define TALKING_VIDEOCALL_SPEAKER       (MODE_VIDEOCALL + SOUND_PATH_SPEAKER)
#define TALKING_VIDEOCALL_HEADSET       (MODE_VIDEOCALL + SOUND_PATH_HEADSET)
#define TALKING_VIDEOCALL_BLUETOOTH     (MODE_VIDEOCALL + SOUND_PATH_BLUETOOTH)

#if 0
/* Sound scenario flags */
#define DEFAULT_GAIN						0X0000

#define NORMAL_MP3_SPEAKER					0x0001
#define NORMAL_MP3_RECEIVER					0x0002	// not use
#define NORMAL_MP3_HEADSET					0x0003
#define NORMAL_VIDEO_SPEAKER				0x0004
#define NORMAL_VIDEO_RECEIVER				0x0005  // not use 
#define NORMAL_VIDEO_HEADSET				0x0006
#define NORMAL_RINGTONE_SPEAKER				0x0007
#define NORMAL_RINGTONE_RECEIVER			0x0008  // not use
#define NORMAL_RINGTONE_HEADSET				0x0009
#define NORMAL_KEYTONE_SPEAKER				0x000A
#define NORMAL_KEYTONE_RECEIVER				0x000B	// not use
#define NORMAL_KEYTONE_HEADSET				0x000C
#define NORMAL_FMRADIO_SPEAKER				0x000D
#define NORMAL_FMRADIO_RECEIVER				0x000E  // not use
#define NORMAL_FMRADIO_HEADSET				0x000F

#define TALK_VOICE_SPEAKER					0x0010
#define TALK_VOICE_RECEIVER					0x0011
#define TALK_VOICE_HEADSET					0x0012
#define TALK_VOICE_BTHANDSFREE				0x0013
#define TALK_VIDEO_SPEAKER					0x0014
#define TALK_VIDEO_RECEIVER					0x0015
#define TALK_VIDEO_HEADSET					0x0016
#define TALK_VIDEO_BTHANDSFREE				0x0017

#define REC_NORMAL_VOICE_KEYMIC				0x0018
#define REC_NORMAL_VOICE_EARMIC				0x0019
#define REC_NORMAL_VOICE_BTHANDSFREEMIC		0x001A	// not use
#define REC_NORMAL_VIDEO_KEYMIC				0x001B
#define REC_NORMAL_VIDEO_EARMIC				0x001C
#define REC_NORMAL_VIDEO_BTHANDSFREEMIC		0x001D	// not use
#define REC_NORMAL_FMRADIO					0x001E  // not use

#define REC_TALK_VOICE_KEYMIC				0x001F	// not use
#define REC_TALK_VOICE_EARMIC				0x0020  // not use
#define REC_TALK_VOICE_BTHANDSFREEMIC		0x0021  // not use
#define REC_TALK_VIDEO_KEYMIC				0x0022  // not use
#define REC_TALK_VIDEO_EARMIC				0x0023  // not use
#define REC_TALK_VIDEO_BTHANDSFREEMIC		0x0024  // not use

#define NORMAL_RINGTONE_BT					0x0030
#define NORMAL_KEYTONE_BT					0x0031
#define NORMAL_RINGTONE_DUALMODE			0x0032
#define NORMAL_KEYTONE_DUALMODE				0x0033
#endif

struct gain_info_t {
	int flag;
	int reg;
	int gain;
};

#define GAIN_TABLE_NUM  32
#define GAIN_POINT_NUM	20

extern struct gain_info_t sound_scenario_table[GAIN_TABLE_NUM][GAIN_POINT_NUM];

