***************
*** 18,45 ****
  obj-$(CONFIG_USB_ATMEL_USBA)	+= atmel_usba_udc.o
  obj-$(CONFIG_USB_FSL_USB2)	+= fsl_usb2_udc.o
  obj-$(CONFIG_USB_M66592)	+= m66592-udc.o
  
  #
  # USB gadget drivers
  #
- C_UTILS =	composite.o usbstring.o config.o epautoconf.o
- 
- g_zero-objs			:= zero.o f_sourcesink.o f_loopback.o $(C_UTILS)
- g_ether-objs			:= ether.o u_ether.o f_subset.o f_ecm.o $(C_UTILS)
- g_serial-objs			:= serial.o u_serial.o f_acm.o f_serial.o $(C_UTILS)
- g_midi-objs			:= gmidi.o usbstring.o config.o epautoconf.o
  gadgetfs-objs			:= inode.o
- g_file_storage-objs		:= file_storage.o usbstring.o config.o \
- 					epautoconf.o
- g_printer-objs			:= printer.o usbstring.o config.o \
- 					epautoconf.o
- g_cdc-objs			:= cdc2.o u_ether.o f_ecm.o \
- 					u_serial.o f_acm.o $(C_UTILS)
  
- ifeq ($(CONFIG_USB_ETH_RNDIS),y)
- 	g_ether-objs		+= f_rndis.o rndis.o
- endif
-  
  obj-$(CONFIG_USB_ZERO)		+= g_zero.o
  obj-$(CONFIG_USB_ETH)		+= g_ether.o
  obj-$(CONFIG_USB_GADGETFS)	+= gadgetfs.o
--- 18,37 ----
  obj-$(CONFIG_USB_ATMEL_USBA)	+= atmel_usba_udc.o
  obj-$(CONFIG_USB_FSL_USB2)	+= fsl_usb2_udc.o
  obj-$(CONFIG_USB_M66592)	+= m66592-udc.o
+ obj-$(CONFIG_USB_FSL_QE)	+= fsl_qe_udc.o
  
  #
  # USB gadget drivers
  #
+ g_zero-objs			:= zero.o
+ g_ether-objs			:= ether.o
+ g_serial-objs			:= serial.o
+ g_midi-objs			:= gmidi.o
  gadgetfs-objs			:= inode.o
+ g_file_storage-objs		:= file_storage.o
+ g_printer-objs			:= printer.o
+ g_cdc-objs			:= cdc2.o
  
  obj-$(CONFIG_USB_ZERO)		+= g_zero.o
  obj-$(CONFIG_USB_ETH)		+= g_ether.o
  obj-$(CONFIG_USB_GADGETFS)	+= gadgetfs.o
