#
#   Makefile for eXtended Sector Remapper (TinyBML) driver on kernel 2.6
#
#   Copyright(C) 2004-2009, Samsung Electronics, Co., Ltd.
#   This file is licensed under GPLv2.
#

# tiny base module
obj-$(CONFIG_RFS_TINYBML)			+= tiny.o

# for tiny bml
tiny-objs	:= tiny_base.o tbml_block.o tbml_blkdev.o

# This objects came from tbml, It will be never modified.
tiny-objs	+= TinyBML/tbml_interface.o TinyBML/gbbm.o TinyBML/onenand_lld.o TinyBML/onenand_lld_asm.o
tiny-objs	+= adapt/LinuxOAM.o adapt/onenand_interface.o

